#!/bin/bash
set -e

while [[ $# > 0  ]]
do
    case $1 in
        --source-paths)
            args="$args $2"
            shift
            shift
            ;;
        *)
            args="$1 $args"
            shift
            ;;
    esac
done

xCompile() {
    output=js/$1.js
    case "$1" in
        *.kts) kotlinc-js -script $1 ;;
        *.kt) kotlinc-js -output $output $1 $2 -module-kind commonjs
    esac
    echo $output
}

echo $(xCompile $args)
